@startuml

class Person {
  name: String
  vorname: String
  geburtsdatum: Date
  email: String
}

class Student{
  matrikelnummer : Integer
  semester: Integer
  fach: String

}

class Pruefung {
  pruefungsnummer: Integer
  bezeichnung: String
  pruefungsdatum: Date

}

class Dozent {
  personalnummer: Integer
}

Student -up-> Person
Dozent -up-> Person
Dozent -- Pruefung: > leitet
Student "0..*" - "0..*" Pruefung: > nimmt teil an
(Student, Pruefung) .. Pruefungsleistung

class Pruefungsleistung {
  note: Float
  status: Pruefungsstatus
  semester: Integer
}

enum Pruefungsstatus {
  ANGEMELDET
  ABGEMELDET
  BESTANDEN
  NICHT_BESTANDEN
}

@enduml
